[package]
name = "amsdal-glue-connections-core"
version = "0.2.0-rc.2"
edition = "2021"

[lib]
name = "_sql_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }
qcraft = { version = "3.2.0", features = ["postgres", "sqlite"] }
serde_json = { version = "1", features = ["preserve_order", "arbitrary_precision"] }
thiserror = "2"
