[package]
name = "amsdal-glue-connections-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "_sql_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
qcraft = { version = "3.1.0", features = ["postgres", "sqlite"] }
serde_json = "1"
thiserror = "2"
