version: '3.8'

volumes:
  customers_db:
    driver: local
  orders_db:
    driver: local

services:
  customers_db:
    image: library/postgres:16
    volumes:
      - "customers_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name_1
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  orders_db:
    image: library/postgres:16
    volumes:
      - "orders_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name_2
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
