services:
  write_db:
    image: library/postgres:16
    environment:
      POSTGRES_DB: write_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  read_db:
    image: library/postgres:16
    environment:
      POSTGRES_DB: read_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
