version: '3.8'

volumes:
  pg_data_existing:
    driver: local
  pg_data_new:
    driver: local

services:
  write_db:
    image: library/postgres:16
    volumes:
      - "pg_data_write:/var/lib/postgresql/data"
      - "./existing-db-dump.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      POSTGRES_DB: db_name_1
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  read_db:
    image: library/postgres:16
    volumes:
      - "pg_data_read:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name_2
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"
