name: Benchmarks

on:
  push:
    branches:
      - master

jobs:
  connections-benchmark:
    name: Connections benchmark
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    env:
      PYTHON: ${{ matrix.python-version }}
      DEPS: yes

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Run tests
        run: |
          cd libs/connections
          hatch run benchmark --benchmark-json=connections-output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Connections Benchmark
          tool: pytest
          output-file-path: connections-output.json
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "connections_benchmark"
          auto-push: true
          max-items-in-chart: 100
          alert-threshold: '200%'
          comment-on-alert: true

  sql-parser-benchmark:
    name: SQL Parser benchmark
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    env:
      PYTHON: ${{ matrix.python-version }}
      DEPS: yes

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Run tests
        run: |
          cd libs/sql-parser
          hatch run benchmark --benchmark-json=sql-parser-output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: SQL Parser Benchmark
          tool: pytest
          output-file-path: sql-parser-output.json
          gh-pages-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "sql_parser_benchmark"
          auto-push: true
          max-items-in-chart: 100
          alert-threshold: '200%'
          comment-on-alert: true