name: Release - SQL Parser

on:
  push:
    tags:
      - 'sql-parser/v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build and compile
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    env:
      PYTHON: ${{ matrix.python-version }}
      DEPS: yes

    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Build
        run: cd libs/sql-parser && hatch build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: libs/sql-parser/dist/

  publish:
    name: Publish to PyPi
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: libs/sql-parser/dist/

      - name: Branch info
        id: branch_info
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Publish
        run: |
          cd libs/sql-parser && hatch publish --user ${{ secrets.PYPI_USERNAME }} --auth ${{ secrets.PYPI_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: libs/sql-parser/dist/*
          name: ${{ steps.branch_info.outputs.SOURCE_TAG }}
          body_path: libs/sql-parser/latest-changelogs.md
          draft: false
          prerelease: false
