name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - tests_ci_cd

jobs:
  amsdal_glue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Hatch run all
        run: |
          cd libs/amsdal-glue
          hatch env prune
          hatch run all

      - name: Hatch run test
        run: |
          cd libs/connections
          hatch run test

  connections:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Hatch run all
        run: |
          cd libs/connections
          hatch env prune
          hatch run all

      - name: Hatch run test
        run: |
          cd libs/connections
          hatch run test

  core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install hatch
        run: |
          python -m pip install hatch

      - name: Hatch run all
        run: |
          cd libs/core
          hatch env prune
          hatch run all

      - name: Hatch run test
        run: |
          cd libs/core
          hatch run test
